export enum Index {
  TIMESTAMP,
  PRESSURE,
  TEMPERATURE,
  ACCELERATION_X,
  ACCELERATION_Y,
  ACCELERATION_Z,
  MAGNETIC_X,
  MAGNETIC_Y,
  MAGNETIC_Z,
  RSSI,
  ROCKET_LAT,
  ROCKET_LON,
  BASE_LAT,
  BASE_LON,
  // BASE_GPS_QUALITY =  14,
  // BASE_GPS_NUM_SATS = 15,
  //Calculated values
  ALTITUDE,
  VELOCITY,
  PITCH,
  ROLL,
  YAW,
  DISTANCE,
  BEARING,
}

export const SEA_LEVEL_PRESSURE = 1014.050964
