export enum Index {
  TIMESTAMP,
  PRESSURE,
  TEMPERATURE,
  ACCELERATION_X,
  ACCELERATION_Y,
  ACCELERATION_Z,
  MAGNETIC_X,
  MAGNETIC_Y,
  MAGNETIC_Z,
  ROCKET_LAT,
  ROCKET_LON,
  ROCKET_GPS_QUALITY,
  ROCKET_GPS_NUM_SATS,
  RSSI,
  BASE_LAT,
  BASE_LON,
  BASE_GPS_QUALITY,
  BASE_GPS_NUM_SATS,
  //Calculated values
  ALTITUDE,
  VELOCITY,
  PITCH,
  ROLL,
  YAW,
  DISTANCE,
  BEARING,
}

export const SEA_LEVEL_PRESSURE = 1014.050964

export const CSV_HEADERS: string[] = [
  'Timestamp',
  'Pressure',
  'Temperature',
  'Acceleration X',
  'Acceleration Y',
  'Acceleration Z',
  'Magnetic X',
  'Magnetic Y',
  'Magnetic Z',
  'Rocket Latitude',
  'Rocket Longitude',
  'Rocket GPS Quality',
  'Rocket GPS Num Sats',
  'RSSI',
  'Base Latitude',
  'Base Longitude',
  'Base GPS Quality',
  'Base GPS Num Sats',
  'Altitude',
  'Velocity',
  'Pitch',
  'Roll',
  'Yaw',
  'Distance',
  'Bearing'
]
